### ISSUE TITLE
Using SFBPopover in a SwiftUI App

### ISSUE THREAD

**Issue by saket** [sbooth/SFBPopovers#14]
In a [SwiftUI App](https://developer.apple.com/documentation/swiftui/app) where there is no explicit creation of a `NSWindow`, what would be the recommended way of displaying an `SFBPopover`?

**Comment by sbooth** [comment]
This is a good question but unfortunately I don't know enough about SwiftUI on macOS to have an answer. Searching turned up a few answers on StackOverflow about creating a hosted window but I don't know if that approach suits your requirements.

**Comment by saket** [comment]
It doesn't actually because I wanna show my _sole_ window inside a popup 😄 . I'm using `NSPopover`, but I don't like its design.

**Comment by sbooth** [comment]
I don't know enough about SwiftUI on macOS to have an answer for this, sorry.
