### ISSUE TITLE
dyld: Library not loaded:  image not found error???

### ISSUE THREAD

**Issue by lunarbase** [sbooth/SFBPopovers#6]
This is the message I get when I try to use your control.

**dyld: Library not loaded: @rpath/SFBPopovers.framework/Versions/A/SFBPopovers
  Referenced from: /Users/user/Library/Developer/Xcode/DerivedData/MyApp-cwztxqahwxiknaedsuvftljxeodr/Build/Products/Debug/MyApp.app/Contents/MacOS/MyApp
  Reason: image not found**

image? what image?

**Comment by sbooth** [comment]
The image it's referring to is the compiled version of the framework.  To get this to work in your project you need to add a copy frameworks build phase and make sure that `SFBPopovers.framework` is included in it.
![screen shot 2015-01-01 at 9 25 05 am](https://cloud.githubusercontent.com/assets/9965/5592339/286abbf6-9198-11e4-91c8-650ebf498c91.png)

**Comment by lunarbase** [comment]
Yes, it is included but even so the error shows. It awful how bad Xcode is. I ended copying the classes to the project directly. Thanks.

**Comment by sbooth** [comment]
The other part of adding the compiled framework to your project is setting `Runpath Search Paths` to `@loader_path/../Frameworks` in your build settings.
